services:
    Happyr\Auth0Bundle\Security\Authentication\Provider\SSOProvider:
        arguments: [~, '@Auth0\SDK\API\Authentication']
        public: false

    Happyr\Auth0Bundle\Security\Firewall\SSOListener:
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
          - [ 'setAuthenticationApi', ['@Auth0\SDK\API\Authentication']]
          - [ 'setClientSecret', ['%auth0.client_secret%']]
          - [ 'setCsrfProtection', ['@Happyr\Auth0Bundle\Security\CsrfProtection']]

    Happyr\Auth0Bundle\Security\EntryPoint\SSOEntryPoint:
        arguments:
            - '@security.http_utils'
            - '@Happyr\Auth0Bundle\SSOUrlGenerator'
            - ~
            - ~
            - ~
        abstract: true

    Happyr\Auth0Bundle\Security\Authentication\Provider\NullProvider:
        public: false

    Happyr\Auth0Bundle\Security\Firewall\Auth0LogoutListener:
        parent: security.logout_listener
        abstract: true
        calls:
            - [ 'setAuth0Domain', ['%auth0.domain%']]

    happyr.auth0.security.authentication.provider.sso: '@Happyr\Auth0Bundle\Security\Authentication\Provider\SSOProvider'
    happyr.auth0.security.authentication.listener.sso: '@Happyr\Auth0Bundle\Security\Firewall\SSOListener'
    happyr.auth0.security.authentication.entry_point.oauth: '@Happyr\Auth0Bundle\Security\EntryPoint\SSOEntryPoint'
    happyr.auth0.security.authentication.provider.null: '@Happyr\Auth0Bundle\Security\Authentication\Provider\NullProvider'
    happyr.auth0.security.authentication.listener.logout: '@Happyr\Auth0Bundle\Security\Firewall\Auth0LogoutListener'
