services:
    happyr.auth0.security.authentication.provider.sso:
        class: Happyr\Auth0Bundle\Security\Authentication\Provider\SSOProvider
        arguments: [~, '@happyr.auth0.api.authentication']
        public: false

    happyr.auth0.security.authentication.listener.sso:
        class: Happyr\Auth0Bundle\Security\Firewall\SSOListener
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
          - [ 'setAuthenticationApi', ["@happyr.auth0.api.authentication"]]
          - [ 'setCsrfTokenManager', ["@security.csrf.token_manager"]]

    happyr.auth0.security.authentication.entry_point.oauth:
        class: Happyr\Auth0Bundle\Security\EntryPoint\SSOEntryPoint
        arguments:
            - "@security.csrf.token_manager"
            - "@security.http_utils"
            - "%auth0.client_id%"
            - "%auth0.domain%"
            - ~ # CSRF Protection set by configuration
        abstract: true
