services:
    happyr.auth0.security.authentication.provider.sso:
        class: Happyr\Auth0Bundle\Security\Authentication\Provider\SSOProvider
        arguments: [~, '@happyr.auth0.api.authentication']
        public: false

    happyr.auth0.security.authentication.listener.sso:
        class: Happyr\Auth0Bundle\Security\Firewall\SSOListener
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
          - [ 'setAuthenticationApi', ["@happyr.auth0.api.authentication"]]
          - [ 'setCsrfTokenManager', ["@security.csrf.token_manager"]]
          - [ 'setClientSecret', ['%auth0.client_secret%']]

    happyr.auth0.security.authentication.entry_point.oauth:
        class: Happyr\Auth0Bundle\Security\EntryPoint\SSOEntryPoint
        arguments:
            - ~ # CsrfTokenManager
            - "@security.http_utils"
            - "@happyr_auth0.sso_url_generator"
            - ~
            - ~
            - ~
        abstract: true

    happyr.auth0.security.authentication.provider.null:
        class: Happyr\Auth0Bundle\Security\Authentication\Provider\NullProvider
        public: false

    happyr.auth0.security.authentication.listener.logout:
        class: Happyr\Auth0Bundle\Security\Firewall\Auth0LogoutListener
        parent: security.logout_listener
        abstract: true
        calls:
            - [ 'setAuth0Domain', ["%auth0.domain%"]]
