
services:
    happyr.auth0.api.authentication:
        class: Auth0\SDK\API\Authentication
        arguments:
            - "https://%auth0.domain%"
            - "%auth0.client_id%"
            - "%auth0.client_secret%"
            - ~ #audience
            - ~ #scope
            - ~ #httpclient

    happyr.auth0.api.management.factory:
        class: Happyr\Auth0Bundle\Factory\ManagementFactory
        arguments:
            - "@happyr.auth0.api.authentication"
            - "%auth0.domain%"
            - "@?auth0.cache"
            - ~ #httpclient
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: happyr_auth0 }

    happyr.auth0.api.management:
        class: Auth0\SDK\API\Management
        factory: ["@happyr.auth0.api.management.factory", "create"]

    happyr.auth0.twig.extension.state_parameter:
        class: Happyr\Auth0Bundle\Twig\StateParameterExtension
        arguments:
            - ~ #csrfTokenManager
        tags:
            - { name: twig.extension }
