
services:
    Auth0\SDK\API\Authentication:
        arguments:
            - 'https://%auth0.domain%'
            - '%auth0.client_id%'
            - '%auth0.client_secret%'
            - ~ #audience
            - ~ #scope
            - ~ #httpclient

    Happyr\Auth0Bundle\Factory\ManagementFactory:
        arguments:
            - '@Auth0\SDK\API\Authentication'
            - '%auth0.domain%'
            - '@?auth0.cache'
            - ~ #httpclient
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: happyr_auth0 }

    Auth0\SDK\API\Management:
        factory: ['@Happyr\Auth0Bundle\Factory\ManagementFactory', 'create']

    Happyr\Auth0Bundle\Twig\Auth0Extension:
        arguments:
            - '%auth0.scope%'
            - '@Happyr\Auth0Bundle\SSOUrlGenerator'
            - '%auth0.domain%'
            - '%auth0.client_id%'
            - '@Happyr\Auth0Bundle\Security\CsrfProtection'
        tags:
            - { name: twig.extension }

    Happyr\Auth0Bundle\SSOUrlGenerator:
        arguments:
            - '%auth0.domain%'
            - '%auth0.client_id%'
            - '%auth0.scope%'
            - '@Happyr\Auth0Bundle\Security\CsrfProtection'

    Happyr\Auth0Bundle\Security\CsrfProtection:
        arguments:
            - ~ # csrf protection flag
            - ~ # csrf token manager

    happyr.auth0.api.authentication: '@Auth0\SDK\API\Authentication'
    happyr.auth0.api.management.factory: '@Happyr\Auth0Bundle\Factory\ManagementFactory'
    happyr.auth0.api.management: '@Auth0\SDK\API\Management'
    happyr.auth0.twig.extension: '@Happyr\Auth0Bundle\Twig\Auth0Extension'
    happyr.auth0.sso_url_generator: '@Happyr\Auth0Bundle\SSOUrlGenerator'
    happyr.auth0.security.csrf_protection: '@Happyr\Auth0Bundle\Security\CsrfProtection'
