
services:
    happyr.auth0.api.authentication:
        class: Auth0\SDK\API\Authentication
        arguments:
            - "https://%auth0.domain%"
            - "%auth0.client_id%"
            - "%auth0.client_secret%"
            - ~ #audience
            - ~ #scope
            - ~ #httpclient

    happyr.auth0.api.management.factory:
        class: Happyr\Auth0Bundle\Factory\ManagementFactory
        arguments:
            - "@happyr.auth0.api.authentication"
            - "%auth0.domain%"
            - "@?auth0.cache"
            - ~ #httpclient
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: happyr_auth0 }

    happyr.auth0.api.management:
        class: Auth0\SDK\API\Management
        factory: ["@happyr.auth0.api.management.factory", "create"]

    happyr.auth0.twig.extension:
        class: Happyr\Auth0Bundle\Twig\Auth0Extension
        arguments:
            - "%auth0.scope%"
            - "@happyr_auth0.sso_url_generator"
            - "%auth0.domain%"
            - "%auth0.client_id%"
            - "@happyr.auth0.security.csrf_protection"
        tags:
            - { name: twig.extension }

    happyr_auth0.sso_url_generator:
        class: Happyr\Auth0Bundle\SSOUrlGenerator
        arguments:
            - "%auth0.domain%"
            - "%auth0.client_id%"
            - "%auth0.scope%"
            - "@happyr.auth0.security.csrf_protection"

    happyr.auth0.security.csrf_protection:
        class: Happyr\Auth0Bundle\Security\CsrfProtection
        arguments:
            - ~ # csrf protection flag
            - ~ # csrf token manager
